### ISSUE TITLE
Ther's no way to change text style for title and text

### ISSUE THREAD

**Issue by MSatyam-Mishra** [PanaraStudios/panaradialogs#12]
This dialog box has beutiful ui but lacks simple features like changing text styles.

**Comment by CodeWithKamal** [comment]
That's how it's built. You can either use built in UI or create your own using PanaraCustomDialog so you can still use animations but can create Custom UI matching to your apps theme.

**Comment by CodeWithKamal** [comment]
That's not issue, that's feature.
