### ISSUE TITLE
Feature to allow no image

### ISSUE THREAD

**Issue by litzbalane2017** [PanaraStudios/panaradialogs#2]
Good Day.

In some use cases, it would be great if there is a way to simply not have the image taking up space, if there is no image attached.

Looking forward to this.

Thank you.

**Comment by panarastudio** [comment]
@litzbalane2017  Thanks for your feedback, we will work on it!

**Comment by CodeWithKamal** [comment]
@litzbalane2017 No Image feature is now available, upgrade the panara_dialogs to v0.1.4
