### ISSUE TITLE
Default images not included in pub?

### ISSUE THREAD

**Issue by alguintu** [PanaraStudios/panaradialogs#3]
Are the default images shown in the screenshots not included in the pub?

Expectation:
![image](https://user-images.githubusercontent.com/6581480/179462844-3f215300-b4b4-4337-ae50-2cbc10e13a40.png)

Result: 
![image](https://user-images.githubusercontent.com/6581480/179462752-bb41ef77-f996-45cf-884c-1e378b5a4b13.png)
```
======== Exception caught by image resource service ================================================
The following assertion was thrown resolving an image codec:
Unable to load asset: packages/panaradialogs/assets/confirm.png

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:237:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:658:14)
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "packages/panaradialogs/assets/confirm.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#f2b28(), name: "packages/panaradialogs/assets/confirm.png", scale: 1.0)
====================================================================================================
```

**Comment by CodeWithKamal** [comment]
@alguintu  Hi Thanks for reporting this issue, we just noticed that. let me push the fix in a moment,.

**Comment by CodeWithKamal** [comment]
@alguintu Please use version 0.1.2, we have fixed this issue.

**Comment by CodeWithKamal** [comment]
> @alguintu Please use version 0.1.2, we have fixed this issue.

Just change the version from your pubspec,ymal file.

**Comment by alguintu** [comment]
Tested working right now. Thank you so much!
