### ISSUE TITLE
Add a parameter to allow show custom Text message

### ISSUE THREAD

**Issue by luis-rodas** [PanaraStudios/panaradialogs#4]
Hi!!,

I good idea could be add an extra parameter like 'customMessage' or something like that, to able to add a custom message, by example, a RichText widget to show it

Best regard!!

**Comment by luis-rodas** [comment]
maybe leave as Widget object parameter to able to put anything, like images, text, etc.,

**Comment by CodeWithKamal** [comment]
Hey @luisrodas-digital,

Sure!, added it to our to-do list. we will make the dialogs more customizable in the next updates.

Thanks & regards!

**Comment by lucasdidur** [comment]
@CodeWithKamal when this will come, we are in 2024

**Comment by CodeWithKamal** [comment]
> @CodeWithKamal when this will come, we are in 2024

let me update the whole package this weekend.

**Comment by CodeWithKamal** [comment]
Now with version 0.1.5, you can use `PanaraCustomDialog` which let's you add your own widgets in base/plain PanaraDialogWidget dialog.
