### ISSUE TITLE
Dialog backgroundColor and textStyle

### ISSUE THREAD

**Issue by pramana0361** [PanaraStudios/panaradialogs#7]
Hi developers,
Is there a way to change the dialog background color and text style?

**Comment by CodeWithKamal** [comment]
@pramana0361 we don't have any way yet! we are working on new major release with a lot of customisation options.

**Comment by CodeWithKamal** [comment]
Now with version 0.1.5, you can change dialog background colour as well as just use `PanaraCustomDialog` which let's you add your own widgets in base/plain PanaraDialogWidget dialog.
